packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.23
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  eslint: ^9.9.0
  prettier: ^3.3.3
  "@prisma/client": ^5.20.0
  "prisma": ^5.20.0
  tailwindcss: ^3.4.10
  typescript: ^5.5.4
  zod: ^3.23.8
  "@ianvs/prettier-plugin-sort-imports": ^4.3.1
  "@types/node": ^20.14.15
  "@types/jest": ^29.5.12
  jest: ^29.7.0
  ts-jest: ^29.2.4
  "@jest/globals": ^29.7.0

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
